Models/Atividade.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace PortalAcessibilidade.Models
{
    public class Atividade
    {
        public int Id { get; set; }
        public String Nome { get; set; }
        public String Tipo { get; set; }
        public String Area { get; set; }
        public String Resumo { get; set; }
        public String Descricao { get; set; }
        public String Sintomas { get; set; }
        public String Diagnostico { get; set; }
        public String Thumbnail { get; set; }
        public List<Ferramenta> Ferramentas { get; set; }
        public int IdadeInicial { get; set; }
        public int IdadeFinal { get; set; }
    }
}

Models/ConnectionFactory/PortalDbContext.cs
using Microsoft.EntityFrameworkCore;
using PortalAcessibilidade.Models;

namespace PortalAcessibilidade
{
    public class PortalDbContext : DbContext
    {
        public DbSet<Atividade> Atividades { get; set; }

        public DbSet<Ferramenta> Ferramentas { get; set; }

        public PortalDbContext(DbContextOptions<PortalDbContext> options) : base(options) {}
    }

}

Models/Dao/AtividadeDao.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace PortalAcessibilidade.Models.Dao
{
    public class AtividadeDao
    {

        private PortalDbContext context;

        public AtividadeDao(PortalDbContext context)
        {
            this.context = context;
        }

        public void Adicionar(Atividade atividade)
        {
            context.Atividades.Add(atividade);
            context.SaveChanges();
        }

        public void Atualizar(Atividade atividade)
        {
            context.Atividades.Update(atividade);
            context.SaveChanges();
        }

        public Atividade Procurar(Atividade atividade)
        {
            return context.Atividades.Where(a => a.Equals(atividade)).Include(a => a.Ferramentas).FirstOrDefault<Atividade>();
        }

        public Atividade Procurar(int? id)
        {
            return context.Atividades.Where(a => a.Id.Equals(id)).Include(a => a.Ferramentas).FirstOrDefault<Atividade>();
        }

        public void Remover(Atividade atividade)
        {
            context.Atividades.Remove(atividade);
            context.SaveChanges();
        }

        public IList<Atividade> Listar()
        {
            return context.Atividades.Include(a => a.Ferramentas).ToList();
        }
       
    }
}

Models/Dao/FerramentaDao.cs
using System.Collections.Generic;
using System.Linq;

namespace PortalAcessibilidade.Models.Dao
{
    public class FerramentaDao
    {

        private PortalDbContext context;

        public FerramentaDao(PortalDbContext context)
        {
            this.context = context;
        }

        public void Adicionar(Ferramenta ferramenta)
        {
            context.Ferramentas.Add(ferramenta);
            context.SaveChanges();
        }

        public void Atualizar(Ferramenta ferramenta)
        {
            context.Ferramentas.Update(ferramenta);
            context.SaveChanges();
        }

        public Ferramenta Procurar(Ferramenta ferramenta)
        {
            return context.Ferramentas.Where(a => a.Equals(ferramenta)).FirstOrDefault<Ferramenta>();
        }

        public Ferramenta Procurar(int? id)
        {
            return context.Ferramentas.Where(a => a.Id.Equals(id)).FirstOrDefault<Ferramenta>();
        }

        public void Remover(Ferramenta ferramenta)
        {
            context.Ferramentas.Remove(ferramenta);
            context.SaveChanges();
        }

        public IList<Ferramenta> Listar()
        {
            return context.Ferramentas.ToList();
        }
       
    }
}

Models/ErrorViewModel.cs
using System;

namespace PortalAcessibilidade.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Ferramenta.cs
using System;

namespace PortalAcessibilidade.Models
{
    public class Ferramenta
    {
        public int Id { get; set; }
        public String Nome { get; set; }
        public String Tipo { get; set; }
        public Atividade Atividade { get; set; }
        public String Resumo { get; set; }
        public String Descricao { get; set; }                
        public String Thumbnail { get; set; }
        
    }
}

Controllers/AtividadeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PortalAcessibilidade.Models;
using PortalAcessibilidade.Models.Dao;

namespace PortalAcessibilidade.Controllers
{
    public class AtividadeController : Controller
    {
        private readonly ILogger<AtividadeController> _logger;
        public AtividadeDao Atividades { get; set; }
        public FerramentaDao Ferramentas { get; set; }

        public AtividadeController(ILogger<AtividadeController> logger, AtividadeDao atividadeDao, FerramentaDao ferramentaDao)
        {
            _logger = logger;
            this.Atividades = atividadeDao;
            this.Ferramentas = ferramentaDao;
        }

        public IActionResult Index()
        {                        
            return View();
        }

        public IActionResult AtividadeInfo(int? id)
        {            
            return View("Oftalmologia/Info", Atividades.Procurar(id));
        }

        public IActionResult FerramentaIniciar(int? id)
        {
            Ferramenta ferramenta = Ferramentas.Procurar(id);

            return View("Oftalmologia/Ferramentas/" + ferramenta.Nome, ferramenta);
        }

        public IActionResult FerramentaResultados(int? id)
        {
            Ferramenta ferramenta = Ferramentas.Procurar(id);

            return View("Oftalmologia/Ferramentas/Resultados", ferramenta);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PortalAcessibilidade.Models;
using PortalAcessibilidade.Models.Dao;

namespace PortalAcessibilidade.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public AtividadeDao Atividades { get; set; }

        public HomeController(ILogger<HomeController> logger, AtividadeDao atividadeDao)
        {
            _logger = logger;
            this.Atividades = atividadeDao;
        }

        public IActionResult Index()
        {
            Atividade atividade = new Atividade()
            {
                Nome = "Daltonismo",
                Area = "Oftalmologia",
                IdadeInicial = 8,
                IdadeFinal = 11,
                Tipo = ""
            };

            //Atividades.Adicionar(atividade);

            ViewData.Model = Atividades.Listar();

            return View();
        }

        public IActionResult Politica()
        {
            return View();
        }

        public IActionResult QuemSomos()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Atividade/Oftalmologia/Ferramentas/Holmgreen.cshtml
@model Ferramenta
@{
    ViewData["Title"] = Model.Tipo + Model.Nome;
}

<div class="text-right">
    <h1 class="display-4">@Model.Nome</h1>
    <p>@Model.Tipo</p>
</div>

<div class="row">
    <h1 class="display-4">Instruções</h1>
</div>
<div class="row text-muted">
    <h6 class="mr-4">
        <i class="oi oi-clock" aria-hidden="true"></i>
        <span> Qualquer idade</span>
    </h6>
    <h6 class="mr-4">
        <i class="oi oi-eye" aria-hidden="true"></i>
        <span> Aplicado por Profissional</span>
    </h6>
    <h6>
        <i class="oi oi-project" aria-hidden="true"></i>
        <span> Resultado com grau e tipo</span>
    </h6>
</div>
<div class="row text-justify">
    <p>
        @Model.Descricao
    </p>
</div>
<div class="row">
    <partial name="Oftalmologia/Ferramentas/Shared/_HolmgreenTeste" model="Model" />
</div>

Views/Atividade/Oftalmologia/Ferramentas/Ishihara.cshtml
@model Ferramenta
@{
    ViewData["Title"] = Model.Tipo + Model.Nome;
}

<div class="text-right">
    <h1 class="display-4">@Model.Nome</h1>
    <p>@Model.Tipo</p>
</div>

<div class="row">
    <h1 class="display-4">Instruções</h1>
</div>
<div class="row text-muted">    
    <h6 class="mr-4">
        <i class="oi oi-eye" aria-hidden="true"></i>
        <span> Não é necessário acompanhamento Profissional</span>
    </h6>
    <h6>
        <i class="oi oi-project" aria-hidden="true"></i>
        <span> Resultado com grau e tipo</span>
    </h6>
</div>
<div class="row text-justify">
    <p>
        @Model.Descricao
    </p>
</div>
<div class="row">     
    <partial name="Oftalmologia/Ferramentas/Shared/_IshiharaTeste" model="Model" />
</div>

Views/Atividade/Oftalmologia/Ferramentas/Resultado.cshtml
@model Atividade
@{
    ViewData["Title"] = Model.Area;
}

Views/Atividade/Oftalmologia/Ferramentas/Shared/_HolmgreenTeste.cshtml
@model Ferramenta
    
    <div class="col-md-12" style="margin-bottom: 15px;">
        <div class="card-header"><h3>@Model.Nome</h3></div>        
    </div>

Views/Atividade/Oftalmologia/Ferramentas/Shared/_IshiharaTeste.cshtml
@model Ferramenta
    
                 
           
<div class="col-md-6 text-right">
                
    <h1>Qual número você vê?</h1>   
    <div class="form-group">        
        <input type="text" class="form-control" id="valor" aria-describedby="valor" placeholder="Pode inserir qualquer valor :)">        
    </div>
    <p><a class="btn btn-outline-dark" href="#" role="button">Próximo</a>
       <a class="btn btn-outline-dark" href="#" role="button">Não vejo nenhum número</a></p>
            
</div>
            
<div class="col-md-6 text-left">
                
    <img class="img-fluid" src="~/Images/Atividades/Oftalmologia/Ferramentas/@Model.Nome/02.png" asp-append-version="true" />
            
</div>                        

Views/Atividade/Oftalmologia/Info.cshtml
@model Atividade
@{
    ViewData["Title"] = Model.Area;
}

<div class="text-right">
    <h1 class="display-4">@Model.Area</h1>
    <p>@Model.Nome</p>
</div>

<div class="row">
    <h1 class="display-4">Descrição</h1>
</div>
<div class="row text-muted">
    <h6 class="mr-4">
        <i class="oi oi-clock" aria-hidden="true"></i>
        <span> @Model.IdadeInicial a @Model.IdadeFinal anos</span>
    </h6>
    <h6 class="mr-4">
        <i class="oi oi-eye" aria-hidden="true"></i>
        <span>@Model.Sintomas</span>
    </h6>
    <h6>
        <i class="oi oi-project" aria-hidden="true"></i>
        <span>@Model.Diagnostico</span>
    </h6>
</div>
<div class="row text-justify">
    <p>
        @Model.Descricao
    </p>
</div>
<div class="row">
    @foreach (Ferramenta ferramenta in Model.Ferramentas)
    {
        <partial name="_DisplayFerramenta" model="ferramenta" />
    }
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Principal";
}

    <div class="text-right">
        <h1 class="display-4">Bem Vindo</h1>
        <p>Primeira vez na plataforma? <a href="https://docs.microsoft.com/aspnet/core">Clique aqui e veja como tudo funciona</a>.</p>
    </div>

    <h1 class="display-4 text-left">Últimas Atividades</h1>
    <div class="row">
        @foreach (Atividade atividade in @ViewData.Model)
         {
            <partial name="_DisplayAtividade" model="atividade" />
         }
    </div>    

Views/Home/Politica.cshtml
@{
    ViewData["Title"] = "Política";
}
<h1>@ViewData["Title"]</h1>

<p>A PortalAcessibilidade garante aos usuários seu direito de usufruir de todos recursos apresentados na plataforma afim de promover o bem estar da sociedade através da tecnologia atual e mitigar os problemas causados pelo distânciamento do acesso a consulta profissional....</p>

Views/Home/QuemSomos.cshtml
@{
    ViewData["Title"] = "Quem Somos";
}
<h1>@ViewData["Title"]</h1>

<p>Um grupo de estudantes do 4° ano de Engenharia da Computação que desenvolveram inicialmente uma ferramenta de auxílio a diversos casos de daltonismo...</p>
<div class="col-md-12">

    <img class="img-fluid" src="~/Images/QuemSomos.jpg" asp-append-version="true" />

</div>

<h1>Nossa Pesquisas</h1>

<p> ...</p>

Views/Shared/_DisplayAtividade.cshtml
@model Atividade
    
        <div class="col-md-4" style="margin-bottom: 15px;">
            <div class="card h-100">
                <div class="card-header"><h3>@Model.Area</h3></div>

                <img class="card-img-top" src="~/Images/Atividades/@Model.Area/@Model.Thumbnail" asp-append-version="true" />

                <div class="card-body">
                    <h5 class="card-title">@Model.Nome</h5>
                    <p class="card-text">@Model.Resumo</p>
                    <a asp-controller="Atividade" asp-action="AtividadeInfo" asp-route-id="@Model.Id" class="btn btn-primary">Acessar</a>
                </div>

                <div class="card-footer">
                    <small class="text-muted">Recomendação: @Model.IdadeInicial a @Model.IdadeFinal anos</small>                    
                </div>
            </div>            
        </div>

Views/Shared/_DisplayFerramenta.cshtml
@model Ferramenta
    
        <div class="col-md-4" style="margin-bottom: 15px;">
            <div class="card h-100">
                <div class="card-header"><h3>@Model.Nome</h3></div>

                <img class="card-img-top" src="~/Images/Atividades/@Model.Atividade.Area/Ferramentas/@Model.Thumbnail" asp-append-version="true" />

                <div class="card-body">
                    <h5 class="card-title">@Model.Tipo</h5>
                    <p class="card-text text-justify">@Model.Resumo</p>
                    <a asp-controller="Atividade" asp-action="FerramentaIniciar" asp-route-id="@Model.Id" class="btn btn-primary">Iniciar</a>
                    <a asp-controller="Atividade" asp-action="FerramentaResultados" asp-route-id="@Model.Id" class="btn btn-primary">Resultados</a>
                </div>

                <div class="card-footer">
                    <small class="text-muted">Atualizado há 1h </small>                    
                </div>
            </div>            
        </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PortalAcessibilidade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/open-iconic-master/font/css/open-iconic-bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PortalAcessibilidade</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Principal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="QuemSomos">Quem Somos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Areas">Areas</a>
                        </li>
                        <!--
        <li class="nav-item dropdown">
            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Areas
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" asp-area="" asp-controller="Atividade" asp-action="">Atividades</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="NossasPesquisas">Nossas Pesquisas</a>
            </div>
        </li>
    -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Notificacoes">Notificações <span class="badge badge-pill badge-danger">3</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Configuracoes">Configurações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sair">Sair</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PortalAcessibilidade - <a asp-area="" asp-controller="Home" asp-action="Politica">Política</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>